### ISSUE TITLE
Build problem when building for ESP32

### ISSUE THREAD

**Issue by CoenBlijker** [wollewald/SI1145_WE#1]
HI,

When I build this library for the Arduino framework for a Lolin ESP32 board in the PlatformIO/Visual Code IDE, the compiler is complaining about a redefinition of the enum value SI1145MeasureType 'PS'.

'PS' is already defined in the file 'specreg.h' as follows: #define PS 230

So maybe you could rename this enum variable..

Besides that I am very happy with your work!

Wkr, 

Coen

**Comment by wollewald** [comment]
Hi Coen, I changed all SI1145MeasureTypes. PS --> PS_TYPE, ALS --> ALS_TYPE, etc.. At least it compiles now. I also changed the examples accordingly. Please try it out. Have fun! Wolfgang
